/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.UsuarioDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelContraseña = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelIconoUsuario = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        cajaContrasena = new javax.swing.JPasswordField();
        cajaCorreo = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelContraseña.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(255, 51, 51));
        labelContraseña.setText("Contraseña");
        getContentPane().add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, -1));

        labelCorreo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(255, 51, 51));
        labelCorreo.setText("Usuario");
        getContentPane().add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, -1));

        labelIconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/usuario.png"))); // NOI18N
        getContentPane().add(labelIconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 51, 51));
        labelTitulo.setText("Tutorias ITSJ");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 140, 30));

        cajaContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(cajaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 128, -1));

        cajaCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCorreoActionPerformed(evt);
            }
        });
        cajaCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(cajaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 128, -1));

        btnInicio.setBackground(new java.awt.Color(153, 153, 153));
        btnInicio.setText("Acceder");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 100, 40));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/digital-art-abstract-artwork-1368191-wallhere.com.jpg"))); // NOI18N
        labelFondo.setText("jLabel6");
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 507, 408));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // Obtener el texto de los campos de correo y contraseña
        String correo = cajaCorreo.getText();
        String contrasena = new String(cajaContrasena.getPassword());

        // Crear una instancia del DAO
        UsuarioDAO usuarioDAO = new UsuarioDAO();

        // Verificar el login
        if (usuarioDAO.login(correo, contrasena)) {
            // Mostrar mensaje de éxito
            VentanaAlumos ventana = new VentanaAlumos();
            ventana.setVisible(true);
            
            dispose();
        } else {
            // Mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.", "Error de Login", JOptionPane.ERROR_MESSAGE);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void cajaContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaContrasenaActionPerformed

    private void cajaCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCorreoKeyTyped
        // TODO add your handling code here:
        //Se obtiene el caracter ingresado
        char c = evt.getKeyChar();
         if (Character.isUpperCase(c)) {
        // Cancelamos el evento actual (no escribirá la letra mayúscula)
        evt.consume();
        // Insertamos la versión en minúscula del carácter en el JTextField
        cajaCorreo.setText(cajaCorreo.getText() + Character.toLowerCase(c));
    }else if(!Character.isLetterOrDigit(c) && c != '@' && c != '.'){
        //Si el caracter no es letra, digito, . o @ el evento se realiza
        evt.consume();
    }
        
    }//GEN-LAST:event_cajaCorreoKeyTyped

    private void cajaCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JPasswordField cajaContrasena;
    private javax.swing.JTextField cajaCorreo;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelIconoUsuario;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
